name: Two Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello John
        id: hello
        uses: raulanatol/my-action@master
        with:
          first-name: 'John Doe'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
